/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataType.DataClient;
import DataType.DataProduct;
import DataType.DataPurchase;
import static GUI.DataClientView.clienti;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.table.DefaultTableModel;
import sekegex.Bill;
import sekegex.Client;
import sekegex.User;

/**
 *
 * @author jopime
 */
public class CreateBillView extends javax.swing.JFrame {

    /**
     * Creates new form CreateBillView
     */
    public CreateBillView(DataClient data, int idBill) {
        initComponents();
        clienti = data;
        this.setTitle("Modificaion de factura para cliente: " + clienti.name);        
        User usr = User.getInstance();
        billi=new Bill(idBill);
        products = usr.listProducts();
        billproducts=billi.listProductsforbill();
        setFilas1();
        setFilas2();
    }
    
    public CreateBillView(DataClient data) {
        initComponents();
        clienti = data;
        this.setTitle("Cracion de factura para cliente: " + clienti.name);        
        User usr = User.getInstance();
        int idBill=usr.insertBill(data.id);
        billi=new Bill(idBill);
        products = usr.listProducts();
        setFilas1();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdd = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablelist = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnButton.setText("Volver");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        jTableAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Añadir Productos"
            }
        ));
        jTableAdd.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableAdd.setRowHeight(32);
        jScrollPane1.setViewportView(jTableAdd);
        if (jTableAdd.getColumnModel().getColumnCount() > 0) {
            jTableAdd.getColumnModel().getColumn(0).setHeaderValue("Añadir Productos");
        }

        jTablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Cantidad", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelist.setRowHeight(32);
        jScrollPane3.setViewportView(jTablelist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(returnButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
       DataClientView obj = new DataClientView(clienti);
       obj.setSize(getSize());
       obj.setLocation(getLocation());
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_returnButtonMouseClicked

        Action add = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            javax.swing.JTable table = (javax.swing.JTable)e.getSource();
            
            int modelRow = Integer.valueOf(e.getActionCommand()); 
            DataProduct prodi=(DataProduct)products.elementAt(modelRow);
            billi.insertPurchase(prodi.id);
            CreateBillView obj = new CreateBillView(clienti,billi.getData().id_bill);
            obj.setSize(getSize());
            obj.setLocation(getLocation());
            obj.setVisible(true);
            dispose();
        }
    };
        
        Action less = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            javax.swing.JTable table = (javax.swing.JTable)e.getSource();
            
            int modelRow = Integer.valueOf(e.getActionCommand()); 
            DefaultTableModel modelo1 = (DefaultTableModel) jTablelist.getModel();
            modelo1.setValueAt((Integer.valueOf(modelo1.getValueAt(modelRow, 0).toString())-1), modelRow, 2);           
            CreateBillView obj = new CreateBillView(clienti,billi.getData().id_bill);
            obj.setSize(getSize());
            obj.setLocation(getLocation());
            obj.setVisible(true);        }
    };
        private void setFilas1() {
        User usr = User.getInstance();
        DefaultTableModel modelo1 = (DefaultTableModel) jTableAdd.getModel();    

        for(int i=0;i<products.size();i++){
            DataProduct prodi=(DataProduct)products.elementAt(i);
            Object[] datos1 = {prodi.name}; 
            modelo1.addRow(datos1);
        }
        
        ButtonColumn buttonColumn1 = new ButtonColumn(jTableAdd, add, 0);
        buttonColumn1.setMnemonic(KeyEvent.VK_D); 
        }
        private void setFilas2(){
        User usr = User.getInstance();
        DefaultTableModel modelo2 = (DefaultTableModel) jTablelist.getModel();    
            DataProduct prodi,prodj;
        for(int i=0;i<billproducts.size();i++){
             prodi=(DataProduct)billproducts.elementAt(i);
            Object[] datos2 = {prodi.id,prodi.name,1};
            /*
            int j=i;
            int count=1;
            while (j<billproducts.size()){
                prodj=(DataPurchase)billproducts.elementAt(j);
                if(prodj.equals(prodi)){
                    count++;
                    billproducts.removeElementAt(j);
                    datos2[2]=count;              
                }
                else{
                    j++;
                }
            }
            */
            modelo2.addRow(datos2);            
        }
        
        ButtonColumn buttonColumn2 = new ButtonColumn(jTablelist, less, 3);
        buttonColumn2.setMnemonic(KeyEvent.VK_D); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBillView(clienti,billi.getData().id_bill).setVisible(true);
            }
        });
    }

    public static DataClient clienti;
    public Vector products;
    public Vector billproducts=null;
    public static Bill billi;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAdd;
    private javax.swing.JTable jTablelist;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
