/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataType.DataEmployee;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JOptionPane;
import sekegex.Employee;

/**
 *
 * @author Ivan
 */
public class EmployeeView extends javax.swing.JFrame {
    javax.swing.JPanel jPanel1;
    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        logo= new javax.swing.JLabel();
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jrQlLrZf.jpeg"))); // NOI18N
        logo.setSize(100,100);
        logo.setLocation(20, 20);
        add(logo);
        this.setExtendedState(MAXIMIZED_BOTH);
        employeeGeneralView1.setWindow(this);
        paintAll(getGraphics());
        repaint();
    }
    
    public void update(){
        employeeGeneralView1.update();
        employeeGeneralView1.setWindow(this);
    }
    
     public void setActEmp(Employee emp){
        activeEmployee=emp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createEmpPanel1 = new GUI.CreateEmpPanel();
        backButton2 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        showEmpPanel1 = new GUI.ShowEmpPanel();
        backButton3 = new javax.swing.JButton();
        modifyEmpPanel1 = new GUI.ModifyEmpPanel();
        backButton4 = new javax.swing.JButton();
        saveButton1 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        createEmpButton = new javax.swing.JButton();
        employeeGeneralView1 = new GUI.EmployeeGeneralView();

        createEmpPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                createEmpPanel1AncestorResized(evt);
            }
        });

        backButton2.setText("Volver");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        saveButton.setText("Crear");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        showEmpPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                showEmpPanel1AncestorResized(evt);
            }
        });

        backButton3.setText("Volver");
        backButton3.setToolTipText("");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        modifyEmpPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                modifyEmpPanel1AncestorResized(evt);
            }
        });

        backButton4.setText("Volver");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        saveButton1.setText("Guardar");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));

        backButton1.setText("Volver");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        createEmpButton.setText("Crear Empeado");
        createEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmpButtonActionPerformed(evt);
            }
        });

        employeeGeneralView1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                employeeGeneralView1AncestorResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createEmpButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton1))
                    .addComponent(employeeGeneralView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeGeneralView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton1)
                    .addComponent(createEmpButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu obj = new MainMenu();
            obj.setSize(getSize());
            obj.setLocation(getLocation());
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void createEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmpButtonActionPerformed
        // TODO add your handling code here:
        remove(employeeGeneralView1);
        remove(backButton1);
        remove(createEmpButton);
        createEmpPanel1.setSize(250, 230);
        createEmpPanel1.clear();
        createEmpPanel1.setLocation((getWidth()-createEmpPanel1.getWidth())/2,20 );
        add(createEmpPanel1);
        backButton2.setSize(backButton2.getPreferredSize());
        backButton2.setLocation(createEmpPanel1.getX()+createEmpPanel1.getWidth()-backButton2.getPreferredSize().width,createEmpPanel1.getY()+createEmpPanel1.getHeight()+6);
        add(backButton2);
        saveButton.setSize(saveButton.getPreferredSize());
        saveButton.setLocation(createEmpPanel1.getX()+createEmpPanel1.getWidth()-backButton2.getPreferredSize().width-18-saveButton.getPreferredSize().width,createEmpPanel1.getY()+createEmpPanel1.getHeight()+6);
        add(saveButton);
        paintAll(getGraphics());
        repaint();
    }//GEN-LAST:event_createEmpButtonActionPerformed
    
    private void createEmpPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_createEmpPanel1AncestorResized
        // TODO add your handling code here:
        createEmpPanel1.setLocation((getWidth()-createEmpPanel1.getWidth())/2,20 );
        backButton2.setLocation(createEmpPanel1.getX()+createEmpPanel1.getWidth()-backButton2.getPreferredSize().width,createEmpPanel1.getY()+createEmpPanel1.getHeight()+6);
        saveButton.setLocation(createEmpPanel1.getX()+createEmpPanel1.getWidth()-backButton2.getPreferredSize().width-18-saveButton.getPreferredSize().width,createEmpPanel1.getY()+createEmpPanel1.getHeight()+6);
    }//GEN-LAST:event_createEmpPanel1AncestorResized

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        remove(createEmpPanel1);
        remove(backButton2);
        remove(saveButton);
        add(employeeGeneralView1);
        add(backButton1);
        add(createEmpButton);
        paintAll(getGraphics());
        repaint();
    }//GEN-LAST:event_backButton2ActionPerformed

    private void employeeGeneralView1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_employeeGeneralView1AncestorResized
        // TODO add your handling code here
        employeeGeneralView1.setLocation((getWidth()-employeeGeneralView1.getWidth())/2,11 );
        backButton1.setLocation(employeeGeneralView1.getX()+employeeGeneralView1.getWidth()-backButton1.getPreferredSize().width,employeeGeneralView1.getY()+employeeGeneralView1.getHeight()+6);
        createEmpButton.setLocation(employeeGeneralView1.getX()+employeeGeneralView1.getWidth()-backButton1.getPreferredSize().width-18-createEmpButton.getPreferredSize().width,employeeGeneralView1.getY()+employeeGeneralView1.getHeight()+6);
    }//GEN-LAST:event_employeeGeneralView1AncestorResized

    private void showEmpPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_showEmpPanel1AncestorResized
        // TODO add your handling code here:
        showEmpPanel1.setLocation((getWidth()-showEmpPanel1.getWidth())/2,11 );
        backButton3.setLocation(showEmpPanel1.getX()+showEmpPanel1.getWidth()/2,showEmpPanel1.getY()+showEmpPanel1.getHeight()+6);
    }//GEN-LAST:event_showEmpPanel1AncestorResized

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
        // TODO add your handling code here:
        remove(showEmpPanel1);
        remove(backButton3);
        add(employeeGeneralView1);
        add(backButton1);
        add(createEmpButton);
        paintAll(getGraphics());
        repaint();
    }//GEN-LAST:event_backButton3ActionPerformed

    private void modifyEmpPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_modifyEmpPanel1AncestorResized
        // TODO add your handling code here:
        modifyEmpPanel1.setLocation((getWidth()-modifyEmpPanel1.getWidth())/2,11 );
        backButton4.setLocation(modifyEmpPanel1.getX()+modifyEmpPanel1.getWidth()/2,modifyEmpPanel1.getY()+modifyEmpPanel1.getHeight()+6);
        saveButton1.setLocation(modifyEmpPanel1.getX()+modifyEmpPanel1.getWidth()/2-18-saveButton1.getPreferredSize().width,modifyEmpPanel1.getY()+modifyEmpPanel1.getHeight()+6);

    }//GEN-LAST:event_modifyEmpPanel1AncestorResized

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        remove(modifyEmpPanel1);
        remove(backButton4);
        remove(saveButton1);
        add(employeeGeneralView1);
        add(backButton1);
        add(createEmpButton);
        paintAll(getGraphics());
        repaint();
    }//GEN-LAST:event_backButton4ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
        DataEmployee data= modifyEmpPanel1.getData();
        activeEmployee.modifyEmployee(data.dni,data.name,data.surname,data.role);
        remove(modifyEmpPanel1);
        remove(backButton4);
        remove(saveButton1);
        update();
        add(employeeGeneralView1);
        add(backButton1);
        add(createEmpButton);
        paintAll(getGraphics());
        repaint();
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(createEmpPanel1.crear()){
            remove(createEmpPanel1);
            remove(backButton2);
            remove(saveButton);
            update();
            add(employeeGeneralView1);
            add(backButton1);
            add(createEmpButton);
            paintAll(getGraphics());
            repaint();
        }else{
            JOptionPane.showMessageDialog(this,"Tienes que rellenar oblidatoriamente los campos Nombre, Apellidos y Dni(9 caracteres máximo)");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public void showEmployee(Employee emp) {                                                     
        remove(employeeGeneralView1);
        remove(backButton1);
        remove(createEmpButton);
        showEmpPanel1.setSize(500, 162);
        showEmpPanel1.setLocation((getWidth()-showEmpPanel1.getWidth())/2,11 );
        showEmpPanel1.set(emp.getData());
        add(showEmpPanel1);
        backButton3.setSize(backButton3.getPreferredSize());
        backButton3.setLocation(showEmpPanel1.getX()+showEmpPanel1.getWidth()/2,showEmpPanel1.getY()+showEmpPanel1.getHeight()+6);
        add(backButton3);
        paintAll(getGraphics());
        repaint();
    } 
    
    public void modifyEmployee(Employee emp) {
        remove(employeeGeneralView1);
        remove(backButton1);
        remove(createEmpButton);
        modifyEmpPanel1.setSize(500,modifyEmpPanel1.getPreferredSize().height);
        modifyEmpPanel1.clear();
        modifyEmpPanel1.setLocation((getWidth()-modifyEmpPanel1.getWidth())/2,11 );
        modifyEmpPanel1.set(emp);
        add(modifyEmpPanel1);
        backButton4.setSize(backButton4.getPreferredSize());
        backButton4.setLocation(modifyEmpPanel1.getX()+modifyEmpPanel1.getWidth()/2,modifyEmpPanel1.getY()+modifyEmpPanel1.getHeight()+6);
        add(backButton4);
        saveButton1.setSize(saveButton1.getPreferredSize());
        saveButton1.setLocation(modifyEmpPanel1.getX()+modifyEmpPanel1.getWidth()/2-18-saveButton1.getPreferredSize().width,modifyEmpPanel1.getY()+modifyEmpPanel1.getHeight()+6);
        add(saveButton1);
        paintAll(getGraphics());
        repaint();
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    private Employee activeEmployee;
    private javax.swing.JLabel logo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton backButton4;
    private javax.swing.JButton createEmpButton;
    private GUI.CreateEmpPanel createEmpPanel1;
    private GUI.EmployeeGeneralView employeeGeneralView1;
    private GUI.ModifyEmpPanel modifyEmpPanel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private GUI.ShowEmpPanel showEmpPanel1;
    // End of variables declaration//GEN-END:variables
}
