/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataType.DataEmployee;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import sekegex.User;

/**
 *
 * @author Ivan
 */
public class ListEmployee extends javax.swing.JPanel {

    /**
     * Creates new form ListEmployee
     */
    public ListEmployee() {
        usr=User.getInstance();
        initComponents();
        employeespanels=new Vector();
        update();
    }
    
    public void update(){
        for(int i=0; i<employeespanels.size();i++){
            EmployeeOpt employeei=(EmployeeOpt)employeespanels.elementAt(i);
            remove(employeei);
        }
        Vector employees=usr.listEmployees();
        employeespanels=new Vector();
        for(int i=0; i<employees.size();i++){
            DataEmployee employeei=(DataEmployee)employees.elementAt(i);
            employeespanels.add(new EmployeeOpt(employeei));
        }
        int fin=0;
        for(int i=0; i<employeespanels.size();i++){
            EmployeeOpt employeei=(EmployeeOpt)employeespanels.elementAt(i);
            employeei.setSize(500,40);
            employeei.setLocation(0, i*40);
            add(employeei);
            fin++;
        }
        setPreferredSize(new Dimension(450,fin*40));
        paintAll(getGraphics());
        repaint();
    }
    
    public void setWindow(EmployeeView win){
        window=win;
        for(int i=0; i<employeespanels.size();i++){
            ((EmployeeOpt)employeespanels.elementAt(i)).setWindow(window);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private User usr;
private EmployeeView window;
private JLabel jLabel1;
private Vector employeespanels;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
