/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DataType.DataProduct;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sekegex.Product;
import sekegex.User;
/**
 *
 * @author Toshiba PC
 */
public class ModifyProduct extends javax.swing.JFrame {

    /**
     * Creates new form ModifyProduct
     */
    public ModifyProduct(DataProduct data) {
        initComponents();
        usr = User.getInstance();
        product = data;
        NombreProducto.setText(product.name.toString());
        DescripcionProducto.setText(product.description.toString());
        float f = product.amount;
        String s = Float.toString(25.0f);
        ImporteProducto.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        NombreProducto = new javax.swing.JTextField();
        DescripcionProducto = new javax.swing.JTextField();
        ImporteProducto = new javax.swing.JTextField();
        CancelarModificar = new javax.swing.JButton();
        GuardarModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Nombre");

        description.setText("Descripción");

        amount.setText("Importe");

        NombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProductoActionPerformed(evt);
            }
        });

        DescripcionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionProductoActionPerformed(evt);
            }
        });

        ImporteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImporteProductoActionPerformed(evt);
            }
        });

        CancelarModificar.setText("Cancelar");
        CancelarModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarModificarMouseClicked(evt);
            }
        });

        GuardarModificar.setText("Guardar");
        GuardarModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelarModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(description)
                            .addComponent(amount))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DescripcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(NombreProducto)
                            .addComponent(ImporteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description)
                    .addComponent(DescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount)
                    .addComponent(ImporteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarModificar)
                    .addComponent(GuardarModificar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProductoActionPerformed

    private void DescripcionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionProductoActionPerformed

    private void ImporteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImporteProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImporteProductoActionPerformed

    private void CancelarModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarModificarMouseClicked
        // TODO add your handling code here:
        DataProductView obj = new DataProductView(product);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelarModificarMouseClicked

    private void GuardarModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarModificarMouseClicked
        // TODO add your handling code here:
        final String newName = name.getText().toString();
        final String newDescription = description.getText().toString();
        final String newAmount = amount.getText().toString();
        float f = Float.parseFloat(newAmount);

        
        Product p = new Product(product.id);
        JFrame frame = new JFrame();
        
        if(usr.hasLicence(500)){
            p.modifyProduct(newName,newDescription,f);
            JOptionPane.showMessageDialog(frame, "La modificación se ha realizado con éxito", "Datos Actualizados", JOptionPane.INFORMATION_MESSAGE);
            repaint();
            product = p.getData();
        }
        else{
            JOptionPane.showMessageDialog(frame, "No tiene permisos para modificar clientes", "ERROR PERMISOS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarModificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyProduct(product).setVisible(true);
            }
        });
    }
    private static User usr;
    private static DataProduct product;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarModificar;
    private javax.swing.JTextField DescripcionProducto;
    private javax.swing.JButton GuardarModificar;
    private javax.swing.JTextField ImporteProducto;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel description;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
